import { bindings } from '../../src/lib/cms';
import { STOCK_ROOT } from './auth';
export const escapeHtml = (value: string) => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export function stockResponse(body: BodyInit | null, type: string, status = 200, extra: Record<string,string> = {}) {
  const publicOrigin = new URL(bindings().PUBLIC_WEB_ORIGIN || 'https://cdmenciana.es').origin;
  return new Response(body,{status,headers:{'content-type':type,'cache-control':'private, no-store, max-age=0','pragma':'no-cache','x-robots-tag':'noindex, nofollow','x-content-type-options':'nosniff','referrer-policy':'same-origin','content-security-policy':`default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' ${publicOrigin}; font-src 'self' ${publicOrigin}; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'`,...extra}});
}
export const stockJsonResponse = (data: unknown, status = 200) => stockResponse(JSON.stringify(data),'application/json; charset=utf-8',status);
const document = (body: string) => `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#0D2E5B"><title>Control de stock | CD Menciana</title><link rel="stylesheet" href="${STOCK_ROOT}/style.css"></head><body>${body}</body></html>`;
const crest = () => `<img class="crest" src="${escapeHtml((bindings().PUBLIC_WEB_ORIGIN || 'https://cdmenciana.es').replace(/\/$/,''))}/images/escudo-oficial.svg" alt="Escudo del CD Menciana" width="68" height="68">`;
export function loginPage(csrf: string, message = '') {
  return document(`<main class="login-shell"><section class="login-card">${crest()}<p class="eyebrow">CD MENCIANA · PERSONAL DEL CLUB</p><h1>Control de stock</h1><p>Accede para gestionar las existencias de la tienda.</p>${message ? `<p class="notice error" role="alert">${escapeHtml(message)}</p>` : ''}${csrf ? `<form method="post" action="${STOCK_ROOT}/login"><input type="hidden" name="csrf" value="${escapeHtml(csrf)}"><label for="password">Contraseña de administración</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="256"><button type="submit">Entrar</button></form>` : ''}<p class="muted">Acceso privado. La sesión caduca después de 8 horas.</p></section></main>`);
}
export function stockPage(csrf: string, actor: string) {
  return document(`<main class="stock-shell" data-stock data-csrf="${escapeHtml(csrf)}" data-web-origin="${escapeHtml(bindings().PUBLIC_WEB_ORIGIN || 'https://cdmenciana.es')}">
<header class="stock-head"><div class="brand">${crest()}<div><p class="eyebrow">CD MENCIANA · TIENDA</p><h1>Control de stock</h1><p class="muted">Sesión: ${escapeHtml(actor)}</p></div></div><button id="logout" class="secondary" type="button">Cerrar sesión</button></header>
<p id="feedback" class="notice" role="status" aria-live="polite" hidden></p>
<section id="stock-summary" class="summary" aria-label="Resumen del inventario"><p>Cargando inventario…</p></section>
<section id="catalogue-panel"><div class="section-head"><div><p class="eyebrow">INVENTARIO DEL CLUB</p><h2>Productos y existencias</h2></div><button id="refresh" class="secondary" type="button">Actualizar</button></div>
<form id="filters" class="filters" role="search"><label>Buscar por nombre o referencia<input id="stock-search" type="search" placeholder="Nombre o SKU" autocomplete="off"></label><label>Categoría<select id="stock-category"><option value="">Todas las categorías</option></select></label><label>Estado<select id="stock-status"><option value="">Todos los estados</option><option>Disponible</option><option>Stock bajo</option><option>Agotado</option><option>Pendiente de configurar</option><option>Archivado</option></select></label></form>
<p id="result-count" class="muted" aria-live="polite"></p><div id="stock-list"></div></section>
<section id="product-detail" hidden aria-labelledby="detail-title"><div class="section-head"><button id="back" class="secondary" type="button">← Volver al inventario</button><button id="refresh-detail" class="secondary" type="button">Actualizar producto</button></div><div id="detail-heading"></div><p class="muted">El total suma las variantes activas. Las consultas de WhatsApp no descuentan unidades.</p><div class="section-head"><h3>Variantes y tallas</h3><button id="add-variant" type="button">Añadir variante</button></div><div id="variant-list"></div><div class="section-head"><h3>Historial de movimientos</h3><label>Tipo de movimiento<select id="history-filter"><option value="">Todos</option><option value="entry">Entradas</option><option value="exit">Salidas</option><option value="adjust">Recuentos</option></select></label></div><p class="muted">Los movimientos se cargan en bloques de 100. Puedes consultar los anteriores.</p><div id="history-list"></div><button id="history-more" class="secondary" type="button" hidden>Cargar movimientos anteriores</button></section>
<dialog id="edit-dialog" aria-labelledby="edit-title"><div class="section-head"><h2 id="edit-title"></h2><button id="close-dialog" class="secondary" type="button">Cerrar</button></div><form id="edit-form"><div id="form-fields"></div><p id="form-error" class="notice error" role="alert" hidden></p><button id="reload-form" class="secondary" type="button" hidden>Actualizar datos antes de guardar</button><p id="dirty-note" class="muted" hidden>Cambios sin guardar.</p><button id="save" type="submit">Guardar</button></form></dialog>
<noscript><p class="notice error">Activa JavaScript para gestionar el inventario. No se han cargado ni modificado existencias.</p></noscript>
</main><script src="${STOCK_ROOT}/client.js" defer></script>`);
}
