import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const origin = process.argv[2] || 'http://127.0.0.1:8787';
const page = await (await fetch(`${origin}/admin/`)).text();
const csrf = page.match(/data-csrf="([a-f0-9]+)"/)?.[1];
assert.ok(csrf, 'Local admin must be enabled and accessible');
const headers = { origin, 'x-cdm-csrf': csrf, 'content-type': 'application/json' };
async function call(path, method = 'GET', body, expected = 200) {
  const response = await fetch(`${origin}${path}`, { method, headers: method === 'GET' ? {} : headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await response.text();
  assert.equal(response.status, expected, `${method} ${path}: ${text}`);
  return JSON.parse(text);
}
const suffix = crypto.randomUUID().slice(0, 8);
const title = `Prueba local ${suffix}`;
const post = await call('/api/admin/posts/', 'POST', { slug: `smoke-${suffix}`, title, excerpt: 'Noticia de prueba local', body: 'Primer párrafo\n\nSegundo párrafo', category: 'Club', coverPhotoId: null }, 201);
await call('/api/admin/posts/', 'POST', { slug: `smoke-${suffix}`, title, excerpt: 'Repetida', body: 'Texto', category: 'Club' }, 409);
let result = await fetch(`${origin}/api/posts/smoke-${suffix}`); assert.equal(result.status, 404, 'Draft must not be public');
const album = await call('/api/admin/albums/', 'POST', { slug: `album-${suffix}`, title: `Álbum ${suffix}`, description: 'Galería local', postId: post.id, coverPhotoId: null }, 201);
const badForm = new FormData(); badForm.set('web', new Blob(['<svg/>'], { type: 'image/svg+xml' }), 'bad.svg'); badForm.set('thumb', new Blob(['<svg/>'], { type: 'image/svg+xml' }), 'bad.svg'); badForm.set('alt', 'Inválida');
result = await fetch(`${origin}/api/admin/albums/${album.id}/photos`, { method: 'POST', headers: { origin, 'x-cdm-csrf': csrf }, body: badForm }); assert.equal(result.status, 413);
const image = await readFile('public/images/patrocinadores/wedding.webp');
const form = new FormData(); form.set('web', new Blob([image], { type: 'image/webp' }), 'web.webp'); form.set('thumb', new Blob([image], { type: 'image/webp' }), 'thumb.webp'); form.set('alt', 'Fotografía de prueba');
result = await fetch(`${origin}/api/admin/albums/${album.id}/photos`, { method: 'POST', headers: { origin, 'x-cdm-csrf': csrf }, body: form });
const uploadText = await result.text();
assert.equal(result.status, 201, `Upload failed: ${uploadText}`);
const photo = JSON.parse(uploadText);
result = await fetch(`${origin}/media/${photo.id}/web`); assert.equal(result.status, 404, 'Draft image must not be public');
result = await fetch(`${origin}/admin/media/${photo.id}/web`); assert.equal(result.status, 200, 'Draft image must be available in local authorized preview');
await call(`/api/admin/albums/${album.id}`, 'PUT', { slug: `album-${suffix}`, title: `Álbum ${suffix}`, description: 'Galería local', postId: post.id, coverPhotoId: photo.id, version: 2 });
await call(`/api/admin/albums/${album.id}/publish`, 'POST');
await call(`/api/admin/posts/${post.id}`, 'PUT', { slug: `smoke-${suffix}`, title, excerpt: 'Noticia de prueba local', body: 'Primer párrafo\n\nSegundo párrafo', category: 'Club', coverPhotoId: photo.id, version: 1 });
await call(`/api/admin/posts/${post.id}/publish`, 'POST');
result = await fetch(`${origin}/api/posts/smoke-${suffix}`); assert.equal(result.status, 200); assert.match(await result.text(), new RegExp(title));
result = await fetch(`${origin}/media/${photo.id}/web`); assert.equal(result.status, 200);
await call(`/api/admin/posts/${post.id}`, 'PUT', { slug: `smoke-renamed-${suffix}`, title: `${title} editada`, excerpt: 'Cambio no visible', body: 'Nuevo cuerpo', category: 'Club', coverPhotoId: photo.id, version: 2 });
result = await fetch(`${origin}/api/posts/smoke-${suffix}`); const before = await result.text(); assert.match(before, new RegExp(title)); assert.doesNotMatch(before, /Cambio no visible/);
result = await fetch(`${origin}/api/posts/smoke-renamed-${suffix}`); assert.equal(result.status, 404);
await call(`/api/admin/posts/${post.id}`, 'PUT', { slug: `smoke-${suffix}`, title, excerpt: 'Stale', body: 'Stale', category: 'Club', version: 2 }, 409);
await call(`/api/admin/posts/${post.id}/publish`, 'POST');
result = await fetch(`${origin}/api/posts/smoke-renamed-${suffix}`); assert.match(await result.text(), /Cambio no visible/);
result = await fetch(`${origin}/api/posts/smoke-${suffix}`); assert.equal(result.status, 404);
await call(`/api/admin/posts/${post.id}/unpublish`, 'POST');
result = await fetch(`${origin}/api/posts/smoke-renamed-${suffix}`); assert.equal(result.status, 404);
await call(`/api/admin/albums/${album.id}/unpublish`, 'POST');
result = await fetch(`${origin}/media/${photo.id}/web`); assert.equal(result.status, 404, 'Withdrawn image must not be public');
await call(`/api/admin/posts/${post.id}`, 'DELETE');
await call(`/api/admin/albums/${album.id}`, 'DELETE');
const bad = await fetch(`${origin}/api/admin/posts/`, { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: '{}' }); assert.equal(bad.status, 403);
result = await fetch(`${origin}/api/posts`, { headers: { origin: 'http://127.0.0.1:4321' } }); assert.equal(result.headers.get('access-control-allow-origin'), 'http://127.0.0.1:4321');
result = await fetch(`${origin}/api/admin/posts/`, { headers: { origin: 'http://127.0.0.1:4321' } }); assert.equal(result.headers.get('access-control-allow-origin'), null, 'Admin API must not permit cross-origin reads');
console.log('Local CMS smoke flow passed.');
